### ISSUE TITLE
How to pass Custom Header in the each Request? and how to show the Custom Header in the Springdoc ui ?

### ISSUE THREAD

**Issue by javaHelper** [springdoc/springdoc-openapi-demos#13] opened 2020-01-21 10:27 UTC

**Comment by bnasslahsen** [comment] 2020-01-22 09:44
Closed, as duplicate of https://github.com/springdoc/springdoc-openapi/issues/363

**Closed by bnasslahsen** 2020-01-22 09:44 UTC

**Comment by javaHelper** [comment] 2020-01-29 12:50
@bnasslahsen - Thanks for your help so far, however I dont see people are responding to springdoc Open API questions on stackoverflow. Could you please help so that it can be reach to wider people ?
